/*
 * AUTOGENERATED - DON'T EDIT
 * Your edits in this file will be overwritten in the next build!
 * Modify the docusaurus.config.js file at your site's root instead.
 */
export default {
  "title": "Powerduck Docs",
  "tagline": "High-performance OpenAPI tooling and embeddable components",
  "favicon": "img/favicon.svg",
  "url": "https://www.powerduck.com",
  "baseUrl": "/docs/",
  "organizationName": "PowerDuckie",
  "projectName": "powerduck-docs",
  "onBrokenLinks": "warn",
  "markdown": {
    "hooks": {
      "onBrokenMarkdownLinks": "warn",
      "onBrokenMarkdownImages": "throw"
    },
    "format": "mdx",
    "mermaid": false,
    "emoji": true,
    "mdx1Compat": {
      "comments": true,
      "admonitions": true,
      "headingIds": true
    },
    "anchors": {
      "maintainCase": false
    }
  },
  "i18n": {
    "defaultLocale": "en",
    "locales": [
      "en"
    ],
    "path": "i18n",
    "localeConfigs": {}
  },
  "customFields": {
    "description": "Powerduck provides high-performance OpenAPI tooling, embeddable Markdown editors, and developer libraries. Explore our open-source documentation.",
    "keywords": "Powerduck, OpenAPI, Markdown editor, API tools, developer libraries, code generation, MCP server, API testing",
    "author": "POWERDUCK LIMITED"
  },
  "headTags": [
    {
      "tagName": "meta",
      "attributes": {
        "name": "description",
        "content": "Powerduck provides high-performance OpenAPI tooling, embeddable Markdown editors, and developer libraries. Explore our open-source documentation."
      },
      "customElement": false
    },
    {
      "tagName": "meta",
      "attributes": {
        "name": "keywords",
        "content": "Powerduck, OpenAPI, Markdown editor, API tools, developer libraries, code generation, MCP server, API testing"
      },
      "customElement": false
    },
    {
      "tagName": "meta",
      "attributes": {
        "name": "author",
        "content": "POWERDUCK LIMITED"
      },
      "customElement": false
    },
    {
      "tagName": "meta",
      "attributes": {
        "property": "og:title",
        "content": "Powerduck Docs - High-performance OpenAPI tooling"
      },
      "customElement": false
    },
    {
      "tagName": "meta",
      "attributes": {
        "property": "og:description",
        "content": "Explore Powerduck open-source libraries: Markdown editor, OpenAPI CLI, code generation, MCP server, and more."
      },
      "customElement": false
    },
    {
      "tagName": "meta",
      "attributes": {
        "property": "og:type",
        "content": "website"
      },
      "customElement": false
    },
    {
      "tagName": "meta",
      "attributes": {
        "property": "og:url",
        "content": "https://www.powerduck.com/docs/"
      },
      "customElement": false
    },
    {
      "tagName": "meta",
      "attributes": {
        "name": "twitter:card",
        "content": "summary_large_image"
      },
      "customElement": false
    },
    {
      "tagName": "meta",
      "attributes": {
        "name": "twitter:title",
        "content": "Powerduck Docs"
      },
      "customElement": false
    },
    {
      "tagName": "meta",
      "attributes": {
        "name": "twitter:description",
        "content": "High-performance OpenAPI tooling and embeddable components."
      },
      "customElement": false
    },
    {
      "tagName": "link",
      "attributes": {
        "rel": "preconnect",
        "href": "https://fonts.googleapis.com"
      },
      "customElement": false
    },
    {
      "tagName": "link",
      "attributes": {
        "rel": "preconnect",
        "href": "https://fonts.gstatic.com",
        "crossorigin": "anonymous"
      },
      "customElement": false
    }
  ],
  "presets": [
    [
      "classic",
      {
        "docs": {
          "sidebarPath": "./sidebars.js",
          "editUrl": "https://github.com/powerducklab/powerduck-docs/tree/main/",
          "showLastUpdateAuthor": false,
          "showLastUpdateTime": false,
          "routeBasePath": "/"
        },
        "blog": false,
        "theme": {
          "customCss": "./src/css/custom.css"
        },
        "sitemap": {
          "changefreq": "weekly",
          "priority": 0.5,
          "ignorePatterns": [
            "/tags/**"
          ],
          "filename": "sitemap.xml"
        }
      }
    ]
  ],
  "themeConfig": {
    "image": "img/docusaurus-social-card.jpg",
    "colorMode": {
      "defaultMode": "light",
      "disableSwitch": false,
      "respectPrefersColorScheme": true
    },
    "navbar": {
      "title": "Powerduck",
      "logo": {
        "alt": "Powerduck Logo",
        "src": "img/logo.svg",
        "href": "/overview/introduction"
      },
      "items": [
        {
          "type": "docSidebar",
          "sidebarId": "tutorialSidebar",
          "position": "left",
          "label": "Docs"
        },
        {
          "type": "dropdown",
          "label": "Open Source",
          "position": "left",
          "items": [
            {
              "label": "MD Editor",
              "href": "https://www.powerduck.com/opensource/md-editor.html"
            },
            {
              "label": "OpenAPI CLI",
              "href": "https://www.powerduck.com/opensource/openapi-cli.html"
            },
            {
              "label": "OpenAPI Codegen",
              "href": "https://www.powerduck.com/opensource/openapi-codegen.html"
            },
            {
              "label": "OpenAPI Request",
              "href": "https://www.powerduck.com/opensource/openapi-request.html"
            },
            {
              "label": "OpenAPI MCP Server",
              "href": "https://www.powerduck.com/opensource/openapi-mcp-server.html"
            },
            {
              "label": "x-to-openapi",
              "href": "https://www.powerduck.com/opensource/x-to-openapi.html"
            },
            {
              "label": "conf-patch",
              "href": "https://www.powerduck.com/opensource/conf-patch.html"
            }
          ]
        },
        {
          "href": "https://www.powerduck.com",
          "label": "Website",
          "position": "right"
        },
        {
          "href": "https://github.com/powerducklab",
          "position": "right",
          "className": "header-github-link",
          "aria-label": "GitHub repository"
        }
      ],
      "hideOnScroll": false
    },
    "footer": {
      "style": "dark",
      "links": [
        {
          "title": "Docs",
          "items": [
            {
              "label": "Overview",
              "to": "/overview/introduction"
            },
            {
              "label": "MD Editor",
              "to": "/md-editor/introduction"
            },
            {
              "label": "OpenAPI CLI",
              "to": "/openapi-cli/introduction"
            }
          ]
        },
        {
          "title": "Libraries",
          "items": [
            {
              "label": "conf-patch",
              "to": "/conf-patch/introduction"
            },
            {
              "label": "openapi-codegen",
              "to": "/openapi-codegen/introduction"
            },
            {
              "label": "openapi-mcp-server",
              "to": "/openapi-mcp-server/introduction"
            },
            {
              "label": "openapi-request",
              "to": "/openapi-request/introduction"
            },
            {
              "label": "x-to-openapi",
              "to": "/x-to-openapi/introduction"
            }
          ]
        },
        {
          "title": "Community",
          "items": [
            {
              "label": "GitHub",
              "href": "https://github.com/powerducklab"
            },
            {
              "label": "Website",
              "href": "https://www.powerduck.com"
            },
            {
              "label": "Contact",
              "href": "mailto:contact@neatico.com"
            }
          ]
        },
        {
          "title": "Legal",
          "items": [
            {
              "label": "Privacy Policy",
              "href": "https://www.powerduck.com/privacy.html"
            },
            {
              "label": "Terms of Service",
              "href": "https://www.powerduck.com/terms.html"
            },
            {
              "label": "Refund Policy",
              "href": "https://www.powerduck.com/refunds.html"
            }
          ]
        }
      ],
      "copyright": "Copyright © 2026 POWERDUCK LIMITED. Built with Docusaurus."
    },
    "prism": {
      "theme": {
        "plain": {
          "color": "#393A34",
          "backgroundColor": "#f6f8fa"
        },
        "styles": [
          {
            "types": [
              "comment",
              "prolog",
              "doctype",
              "cdata"
            ],
            "style": {
              "color": "#999988",
              "fontStyle": "italic"
            }
          },
          {
            "types": [
              "namespace"
            ],
            "style": {
              "opacity": 0.7
            }
          },
          {
            "types": [
              "string",
              "attr-value"
            ],
            "style": {
              "color": "#e3116c"
            }
          },
          {
            "types": [
              "punctuation",
              "operator"
            ],
            "style": {
              "color": "#393A34"
            }
          },
          {
            "types": [
              "entity",
              "url",
              "symbol",
              "number",
              "boolean",
              "variable",
              "constant",
              "property",
              "regex",
              "inserted"
            ],
            "style": {
              "color": "#36acaa"
            }
          },
          {
            "types": [
              "atrule",
              "keyword",
              "attr-name",
              "selector"
            ],
            "style": {
              "color": "#00a4db"
            }
          },
          {
            "types": [
              "function",
              "deleted",
              "tag"
            ],
            "style": {
              "color": "#d73a49"
            }
          },
          {
            "types": [
              "function-variable"
            ],
            "style": {
              "color": "#6f42c1"
            }
          },
          {
            "types": [
              "tag",
              "selector",
              "keyword"
            ],
            "style": {
              "color": "#00009f"
            }
          }
        ]
      },
      "darkTheme": {
        "plain": {
          "color": "#F8F8F2",
          "backgroundColor": "#282A36"
        },
        "styles": [
          {
            "types": [
              "prolog",
              "constant",
              "builtin"
            ],
            "style": {
              "color": "rgb(189, 147, 249)"
            }
          },
          {
            "types": [
              "inserted",
              "function"
            ],
            "style": {
              "color": "rgb(80, 250, 123)"
            }
          },
          {
            "types": [
              "deleted"
            ],
            "style": {
              "color": "rgb(255, 85, 85)"
            }
          },
          {
            "types": [
              "changed"
            ],
            "style": {
              "color": "rgb(255, 184, 108)"
            }
          },
          {
            "types": [
              "punctuation",
              "symbol"
            ],
            "style": {
              "color": "rgb(248, 248, 242)"
            }
          },
          {
            "types": [
              "string",
              "char",
              "tag",
              "selector"
            ],
            "style": {
              "color": "rgb(255, 121, 198)"
            }
          },
          {
            "types": [
              "keyword",
              "variable"
            ],
            "style": {
              "color": "rgb(189, 147, 249)",
              "fontStyle": "italic"
            }
          },
          {
            "types": [
              "comment"
            ],
            "style": {
              "color": "rgb(98, 114, 164)"
            }
          },
          {
            "types": [
              "attr-name"
            ],
            "style": {
              "color": "rgb(241, 250, 140)"
            }
          }
        ]
      },
      "additionalLanguages": [
        "bash",
        "json",
        "yaml",
        "typescript",
        "javascript",
        "python",
        "go",
        "rust",
        "java",
        "php",
        "ruby",
        "csharp",
        "kotlin",
        "swift",
        "dart",
        "sql"
      ],
      "magicComments": [
        {
          "className": "theme-code-block-highlighted-line",
          "line": "highlight-next-line",
          "block": {
            "start": "highlight-start",
            "end": "highlight-end"
          }
        }
      ]
    },
    "tableOfContents": {
      "minHeadingLevel": 2,
      "maxHeadingLevel": 4
    },
    "docs": {
      "versionPersistence": "localStorage",
      "sidebar": {
        "hideable": false,
        "autoCollapseCategories": false
      }
    },
    "blog": {
      "sidebar": {
        "groupByYear": true
      }
    },
    "metadata": []
  },
  "plugins": [],
  "baseUrlIssueBanner": true,
  "storage": {
    "type": "localStorage",
    "namespace": false
  },
  "future": {
    "v4": {
      "removeLegacyPostBuildHeadAttribute": false,
      "useCssCascadeLayers": false,
      "siteStorageNamespacing": false,
      "fasterByDefault": false,
      "mdx1CompatDisabledByDefault": false
    },
    "faster": {
      "swcJsLoader": false,
      "swcJsMinimizer": false,
      "swcHtmlMinimizer": false,
      "lightningCssMinimizer": false,
      "mdxCrossCompilerCache": false,
      "rspackBundler": false,
      "rspackPersistentCache": false,
      "ssgWorkerThreads": false,
      "gitEagerVcs": false
    },
    "experimental_vcs": {},
    "experimental_router": "browser"
  },
  "onBrokenAnchors": "warn",
  "onDuplicateRoutes": "warn",
  "staticDirectories": [
    "static"
  ],
  "themes": [],
  "scripts": [],
  "stylesheets": [],
  "clientModules": [],
  "titleDelimiter": "|",
  "noIndex": false
};
